### ISSUE TITLE
When copying, the script will not continue to run automatically. It will not continue until the copy is finished, which wastes a lot of time

### ISSUE THREAD

**Issue by coolsd** [Dartellum/chia-madmax-plot_loop#1]
When copying, the script will not continue to run automatically. It will not continue until the copy is finished, which wastes a lot of time

**Comment by Dartellum** [comment]
True. One option is to not have this script to a copy to the final destination but to make another one and run in `cron` to move plots as it finds them on some interval. My main goal was with this was to have it auto find a destination. I also need to test how long a `mv` takes because someone in MadMax's issues said `mv` is faster than `cp` or the mechanism used in `chia-plotter`. Free feel to modify as you need. :smile:
